version: "2"

linters:
  default: none
  enable:
    - bidichk
    - errcheck
    - govet
    - ineffassign
    - makezero
    - misspell
    - modernize
    - revive
    - staticcheck
    - unconvert
    - unqueryvet
    - unused
    - whitespace
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - max-lit-count: "3"
              allow-strs: '""'
              allow-ints: "-1,0,1,2,10,64,100"
              allow-floats: "0.0"
        - name: cognitive-complexity
          arguments:
            - 14  # default of SonarQube
        - name: empty-block
          disabled: true
        - name: exported
          disabled: true
        - name: line-length-limit
          disabled: false
          arguments: [120]
        - name: max-public-structs
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: unhandled-error
          arguments:
            - "fmt.*"
        
  exclusions:
    generated: lax
    rules:
      - linters:
        - lll
        - revive
        source: "^//go:generate"

formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    golines:
      max-len: 120
      shorten-comments: true
      reformat-tags: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true

run:
  allow-parallel-runners: true
  tests: false

severity:
  default: warning